package com.openbounty.dto.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Standard RFC 7807 Problem Details representation for HTTP API error responses.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "Standard RFC 7807 Problem Details error response")
public class ErrorResponse {

    @Schema(description = "URI reference that identifies the problem type", example = "https://api.openbounty.dev/errors/resource-not-found")
    private String type;

    @Schema(description = "Short, human-readable summary of the problem type", example = "Resource Not Found")
    private String title;

    @Schema(description = "HTTP status code generated by the origin server", example = "404")
    private int status;

    @Schema(description = "Human-readable explanation specific to this occurrence of the problem", example = "Bounty with ID 999 does not exist.")
    private String detail;

    @Schema(description = "URI reference that identifies the specific occurrence of the problem", example = "/api/bounties/999")
    private String instance;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
    @Schema(description = "Timestamp when the error occurred", example = "2026-08-31T21:35:00.000Z")
    private LocalDateTime timestamp;

    @Schema(description = "Granular field-level validation errors map (present on 400 Bad Request validation failures)")
    private Map<String, String> errors;
}
